### ISSUE TITLE
Cannot read property "toUpperCase" of undefined

### ISSUE THREAD

**Issue by Dono7** [neilco/twix#7]
Hello ! First of all, thank you for this very lightweight library ! I was bored of using Jquery for basic Ajax calls.

Issue : 
I get this error when I use the `Twix.ajax()` function without specifying any "type" option.

(The example below is the sample getTime example)

![image](https://user-images.githubusercontent.com/35794293/97022865-f4987380-1554-11eb-8845-29e72ffde9da.png)

**Comment by neilco** [comment]
Thanks for reporting this. Fixed in [v1.2](https://github.com/neilco/twix/releases/tag/v1.2).
